# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: informatic memoranda
description: > # this means to ignore newlines until "email:"
   gloria’s field notes on information & technology 

# email: a-mail@mail.mail
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: Gloria Gonzalez
author: Gloria G. Gonzalez
author_image: "/assets/images/author.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: ‘@informaticmonad’

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/informaticmonad
    desc: follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/informaticmonad
    desc:	find me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
